export { default as Rules } from './Rules/index.jsx';
export { default as Schedule } from './Schedule/index.jsx';
export { default as RegistrationForm } from './RegistrationForm/index.jsx';
export { default as ProblemStatements } from './ProblemStatements/index.jsx';
export { default as Home } from './Home/index.jsx';
export { default as Contact } from './Contact/index.jsx';
export { default as SubmissionPortal } from './SubmissionPortal/index.jsx';
export { default as Sponsors } from './Sponsors/index.jsx';
export { default as FAQs } from './FAQs/index.jsx';